services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: food-review-minio

    ports:
      - "${MINIO_API_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"

    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}

    volumes:
      - ./storage/minio:/data

    command: server /data --console-address ":9001"

    restart: unless-stopped

    networks:
      - food-review-network


  postgres:
    image: postgres:16
    container_name: food-review-postgres

    ports:
      - "${POSTGRES_PORT}:5432"

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - ./storage/postgres:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped

    networks:
      - food-review-network


  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: food-review-cloudbeaver

    ports:
      - "${CLOUDBEAVER_PORT}:8978"

    environment:
      CB_SERVER_NAME: ${CLOUDBEAVER_SERVER_NAME}
      CB_SERVER_URL: http://localhost:${CLOUDBEAVER_PORT}

      CB_ADMIN_NAME: ${CLOUDBEAVER_ADMIN_NAME}
      CB_ADMIN_PASSWORD: ${CLOUDBEAVER_ADMIN_PASSWORD}

      CLOUDBEAVER_APP_SUPPORTS_CUSTOM_CONNECTIONS: "true"

    volumes:
      - ./storage/cloudbeaver:/opt/cloudbeaver/workspace

    depends_on:
      postgres:
        condition: service_healthy

    restart: unless-stopped

    networks:
      - food-review-network


networks:
  food-review-network:
    driver: bridge